### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by JustAmalll** [canopas/compose-country-picker#9]
java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.compose.material.ModalBottomSheetKt.rememberModalBottomSheetState, parameter confirmStateChange

**Comment by cp-radhika-s** [comment]
@JustAmalll Thanks for reporting an issue. 
Could you please provide a full stacktrace and steps to reproduce the issue?

**Comment by cp-radhika-s** [comment]
@JustAmalll  We did a few improvements and bug fixes, can you please try with the latest version `1.0.5`?
